### ISSUE TITLE
How to test if PSS is working?

### ISSUE THREAD

**Issue by mwoolweaver** [jaykepeters/Pi-hole_SafeSearch#3]
Is there something that can be searched to test if this is working?

**Comment by mwoolweaver** [comment]
Also this recent p/r https://github.com/pi-hole/pi-hole/pull/2978 might have made this a bit easier?

**Comment by jakenology** [comment]
Yes, I agree that this may make it easier. To test if it is working, you could simply do an nslookup for www.google.com, or `dig +short www.google.com`. Try searching some type of questionable term... I know that with DuckDuckGo, "boobs" (mentioned by another on Pi-hole forums) will not show images. With Google "xxx," it should not show adult sites in the search results.

**Comment by jakenology** [comment]
I assume this all worked out? :)

**Comment by mwoolweaver** [comment]
yes sorry i didnt close
